export declare const IS_WX: boolean;
export declare const SUPPORT_TOUCH: boolean;
export declare const DIRECTION_NONE = 1;
export declare const DIRECTION_LEFT = 2;
export declare const DIRECTION_RIGHT = 4;
export declare const DIRECTION_UP = 8;
export declare const DIRECTION_DOWN = 16;
export declare const DIRECTION_HORIZONTAL: number;
export declare const DIRECTION_VERTICAL: number;
export declare const DIRECTION_ALL: number;
export declare const COMPUTE_INTERVAL = 16;
export declare const CLIENT_X = "clientX";
export declare const CLIENT_Y = "clientY";
export declare const RECOGNIZER_STATUS_POSSIBLE = 1;
export declare const RECOGNIZER_STATUS_BEGAN = 2;
export declare const RECOGNIZER_STATUS_CHANGED = 4;
export declare const RECOGNIZER_STATUS_ENDED = 8;
export declare const RECOGNIZER_STATUS_RECOGNIZED = 8;
export declare const RECOGNIZER_STATUS_CANCELLED = 16;
export declare const RECOGNIZER_STATUS_FAILED = 32;
export declare const INPUT_START = "start";
export declare const INPUT_MOVE = "move";
export declare const INPUT_CANCEL = "cancel";
export declare const INPUT_END = "end";
export declare const NONE = "none";
